<div id="footer">
Really basic instructions:<br>
1) Drag and drop file on to the page header.  (hopefully you drag and drop a valid CSV).<br>
&nbsp;&nbsp;&nbsp;&nbsp;Repeat as often as you woud like.<br>
2) Click on a row to see options.<br>
3) Click on options to activate them.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Edit: Edits row<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Save: Saves changes<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cancel: Throws away changes<br>
&nbsp;&nbsp;&nbsp;&nbsp;Delete: Delete row<br>
&nbsp;&nbsp;&nbsp;&nbsp;Hide: Hide options.<br>
4) Click on "+ Add More information" to add a row manually.<br>
</div>